POST https://localhost:3001/api/users 
Content-Type: application/json

{
  "email": "test@c.com", 
  "name": "rootname", 
  "surname": "rootsurname", 
  "password": "root"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "email": "test@c.com", 
  "password": "root"
}

###
GET http://localhost:3001/api/users/40
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJpYXQiOjE2NzcxOTQxMTYsImV4cCI6MTY3NzIxNTcxNn0.jr6m3pv80ejEl-2VgCUD3HcSti_O_lPslXEQRR8qPzI

###
GET http://localhost:3001/api/users
Content-Type: application/json

###
PATCH http://localhost:3001/api/users
Content-Type: application/json

###
DELETE  http://localhost:3001/api/users/4
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJpYXQiOjE2NzcxOTQxMTYsImV4cCI6MTY3NzIxNTcxNn0.jr6m3pv80ejEl-2VgCUD3HcSti_O_lPslXEQRR8qPzI

###
PUT http://localhost:3001/api/users/2
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJpYXQiOjE2NzcxOTQxMTYsImV4cCI6MTY3NzIxNTcxNn0.jr6m3pv80ejEl-2VgCUD3HcSti_O_lPslXEQRR8qPzI

{
  "name": "newname", 
  "surname": "rose",
  "email": "newmail@example.com",
  "newPassword": "newPassword",
  "currentPassword": "root"
}

###
POST http://localhost:3001/api/decks
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJpYXQiOjE2NzcxOTQxMTYsImV4cCI6MTY3NzIxNTcxNn0.jr6m3pv80ejEl-2VgCUD3HcSti_O_lPslXEQRR8qPzI

###
GET http://localhost:3001/api/decks
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJpYXQiOjE2NzcxOTQxMTYsImV4cCI6MTY3NzIxNTcxNn0.jr6m3pv80ejEl-2VgCUD3HcSti_O_lPslXEQRR8qPzI

###
PUT http://localhost:3001/api/decks/2
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJpYXQiOjE2NzcxOTQxMTYsImV4cCI6MTY3NzIxNTcxNn0.jr6m3pv80ejEl-2VgCUD3HcSti_O_lPslXEQRR8qPzI

{
  "title": "new title"
}

###
DELETE  http://localhost:3001/api/decks/1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJpYXQiOjE2NzcxOTQxMTYsImV4cCI6MTY3NzIxNTcxNn0.jr6m3pv80ejEl-2VgCUD3HcSti_O_lPslXEQRR8qPzI

###
POST http://localhost:3001/api/cards 
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJpYXQiOjE2NzcxOTQxMTYsImV4cCI6MTY3NzIxNTcxNn0.jr6m3pv80ejEl-2VgCUD3HcSti_O_lPslXEQRR8qPzI

{
  "deckId": 4,
  "type": "classic",
  "tags": ["b"],
  "front": "asdfsdf",
  "back": "rfrfrf",
  "audio": ""
}

###
GET http://localhost:3001/api/define/ace
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJpYXQiOjE2NzcxOTQxMTYsImV4cCI6MTY3NzIxNTcxNn0.jr6m3pv80ejEl-2VgCUD3HcSti_O_lPslXEQRR8qPzI


###
GET http://localhost:3001/api/cards 
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJpYXQiOjE2NzcxOTQxMTYsImV4cCI6MTY3NzIxNTcxNn0.jr6m3pv80ejEl-2VgCUD3HcSti_O_lPslXEQRR8qPzI

###
PUT http://localhost:3001/api/cards/144
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJpYXQiOjE2NzcxOTQxMTYsImV4cCI6MTY3NzIxNTcxNn0.jr6m3pv80ejEl-2VgCUD3HcSti_O_lPslXEQRR8qPzI

{ 
  "level": ,
  "front": "ht",
  "audio": ","
}

###
DELETE  http://localhost:3001/api/cards/2
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJpYXQiOjE2NzcxOTQxMTYsImV4cCI6MTY3NzIxNTcxNn0.jr6m3pv80ejEl-2VgCUD3HcSti_O_lPslXEQRR8qPzI



