POST http://localhost:3001/api/users 
Content-Type: application/json

{
  "email": "test@c.com", 
  "name": "rootname", 
  "surname": "rootsurname", 
  "password": "root"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "email": "test@c.com", 
  "password": "root"
}

###
GET http://localhost:3001/api/users/40
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5MjYyOTI2MywiZXhwIjoxNjkyNjUwODYzfQ.bP4i1joRHYli24vLR-4D1_s-hGbabHuqBPPBIRDN5kA

###
GET http://localhost:3001/api/users
Content-Type: application/json

###
PATCH http://localhost:3001/api/users
Content-Type: application/json

###
DELETE  http://localhost:3001/api/users/4
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5MjYyOTI2MywiZXhwIjoxNjkyNjUwODYzfQ.bP4i1joRHYli24vLR-4D1_s-hGbabHuqBPPBIRDN5kA

###
PUT http://localhost:3001/api/users/2
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5MjYyOTI2MywiZXhwIjoxNjkyNjUwODYzfQ.bP4i1joRHYli24vLR-4D1_s-hGbabHuqBPPBIRDN5kA

{
  "name": "newname", 
  "surname": "rose",
  "email": "newmail@example.com",
  "newPassword": "newPassword",
  "currentPassword": "root"
}

###
POST http://localhost:3001/api/decks
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5MjYyOTI2MywiZXhwIjoxNjkyNjUwODYzfQ.bP4i1joRHYli24vLR-4D1_s-hGbabHuqBPPBIRDN5kA

###
GET http://localhost:3001/api/decks
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5MjYyOTI2MywiZXhwIjoxNjkyNjUwODYzfQ.bP4i1joRHYli24vLR-4D1_s-hGbabHuqBPPBIRDN5kA

###
PUT http://localhost:3001/api/decks/2
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5MjYyOTI2MywiZXhwIjoxNjkyNjUwODYzfQ.bP4i1joRHYli24vLR-4D1_s-hGbabHuqBPPBIRDN5kA

{
  "title": "new title"
}

###
DELETE  http://localhost:3001/api/decks/1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5MjYyOTI2MywiZXhwIjoxNjkyNjUwODYzfQ.bP4i1joRHYli24vLR-4D1_s-hGbabHuqBPPBIRDN5kA

###
POST http://localhost:3001/api/cards 
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5MjYyOTI2MywiZXhwIjoxNjkyNjUwODYzfQ.bP4i1joRHYli24vLR-4D1_s-hGbabHuqBPPBIRDN5kA

# {
#   "deckId": 1,
#   "tags": ["b"],
#   "content": { "type": "classic", "front": "frontcard", "back": "backcard"},
#   "audio": ""
# }
{
  "deckId": 1,
  "tags": ["b"],
  "content": { "type": "cloze", "hint": "title", "text": {"hint": true, "word": "false"}},
  "audio": ""
}

###
GET http://localhost:3001/api/define/ace
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5MjYyOTI2MywiZXhwIjoxNjkyNjUwODYzfQ.bP4i1joRHYli24vLR-4D1_s-hGbabHuqBPPBIRDN5kA


###
GET http://localhost:3001/api/cards 
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5MjYyOTI2MywiZXhwIjoxNjkyNjUwODYzfQ.bP4i1joRHYli24vLR-4D1_s-hGbabHuqBPPBIRDN5kA

###
PUT http://localhost:3001/api/cards/144
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5MjYyOTI2MywiZXhwIjoxNjkyNjUwODYzfQ.bP4i1joRHYli24vLR-4D1_s-hGbabHuqBPPBIRDN5kA

{ 
  "level": ,
  "front": "ht",
  "audio": ","
}

###
DELETE  http://localhost:3001/api/cards/2
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5MjYyOTI2MywiZXhwIjoxNjkyNjUwODYzfQ.bP4i1joRHYli24vLR-4D1_s-hGbabHuqBPPBIRDN5kA



